### ISSUE TITLE
new isntallation is not working

### ISSUE THREAD

**Issue by Jarry377** [bassettb/SugarPiDisplay#10]
Hi,
i just installed SugarPi on a new Pi Zero W with the 2,13" Waveshare ePaper HAT. But unfortunately, it is not working....
i followed all the instructions, but after the reboot, nothing is shown on the ePaper, no Webserver is reachable.
can you help?

**Comment by Jarry377** [comment]
it seems, that there is something missing:
after installing some more dependencies, i was able to "fix" it

sudo apt-get install libopenjp2-7-dev
sudo apt install libtiff5

**Comment by bassettb** [comment]
@Jarry377  Glad you figured it out.  I updated my docs also with that change.  How is the screen working for you? Any wishlist items?
I've made a lot of improvements, if you grab the latest commits.

**Comment by seattlebrighton** [comment]
Bassettb - Are there any good troubleshooting steps, in case the display is not updating. I can reach the pi zero via ssh so could look at logs to see what is and isn't working?
Thanks, -Mark

**Comment by bassettb** [comment]
> Bassettb - Are there any good troubleshooting steps, in case the display is not updating. I can reach the pi zero via ssh so could look at logs to see what is and isn't working? Thanks, -Mark

You can look in `/home/pi/.sugarpidisplay/sugarpidisplay.log`
Was it previously working and then it stopped?

**Comment by seattlebrighton** [comment]
I got a new pi zero 2, so started anew. The display isn't updating, but I
manually ran sugarpidisplay.sh to get the web portal running and set the
nightscout configs. I think it's getting a 307 response from nightscout,
but I'm not sure and don't know what to do from here. To find the log file,
I had to change your code for the path since I changed the host name to
piSugar. Now my log file goes to /piSugar/.
Can you help me figure out how to log either gb-from-nightscout-success or
a failure case that would help diagnose the problem?

**Comment by bassettb** [comment]
Status 307 is a redirect.  Are you maybe using an alias URL?  Could you instead use the URL it redirects to?

**Comment by seattlebrighton** [comment]
That'a a good thought, but I'm using the url that nightscout gave me. I'd
like to add some troubleshooting tips to your readme, in case anyone else
has trouble like me. Right now, the setup ends with this:
"

   - SugarPiDisplay/install.sh
   - reboot the Raspberry Pi and SugarPiDisplay should be running

<https://github.com/bassettb/SugarPiDisplay/blob/master/docs/software_setup.md#configuring-sugarpidisplay>Configuring
SugarPiDisplay

   - Once SugarPiDisplay is running,


But I think we could add a few troubleshooting tips to verify that
SugarPiDisplay is running, like a ps -aux | grep -i sugar or something like
that. Then if it's not running, would error logs be sent to
~/.sugarpidisplay/sugarpidisplay.log?
Then, if it's running and not getting to nightscout, are the logs saved to
help troubleshoot that case?
Then, if it's hitting nightscout but not logging in...
Then, if it's logging into nightscout but not getting BG results...
Then, is there any way for code to check if the display is correctly
connected, and log something if the display is messed up?

Thanks for any thought and help. I'm hoping I'm helping others by tracking
these steps down.
-Mark

**Comment by seattlebrighton** [comment]
I just reinstalled on my pi zero 2 and it uninstalled/reinstalled, and then
since I couldn't reach the webserver, I ssh'ed in and ran
sugarpidisplay.sh, which gave this response:

*~/SugarPiDisplay $* ./sugarpidisplay.sh

Clear...

Display: Initializing ||

 * Serving Flask app 'sugarpidisplay.sugarpiconfig' (lazy loading)

 * Environment: production

   WARNING: This is a development server. Do not use it in a production
deployment.

   Use a production WSGI server instead.

 * Debug mode: off

WARNING:werkzeug: * Running on all addresses.

   WARNING: This is a development server. Do not use it in a production
deployment.

INFO:werkzeug: * Running on http://192.168.87.27:8080/ (Press CTRL+C to
quit)

INFO:sugarpidisplay.sugar_pi_app:Wifi IP: 192.168.87.27

Display: 192.168.87.27 ||

ERROR:sugarpidisplay.sugar_pi_app:Exception during login [Errno -2] Name or
service not known

Display: Login Failed || Will Retry


Do you know why this error occurred and what I should do next?

ERROR:sugarpidisplay.sugar_pi_app:Exception during login [Errno -2] Name or
service not known

Display: Login Failed || Will Retry


Thanks, -Mark

**Comment by bassettb** [comment]
I reproduced your problem.  Here's the fix: include the "https://" scheme in your nightscout URL.

**Comment by seattlebrighton** [comment]
Thanks! Should the config.json look like this?

{

    "data_source": "nightscout",

    "time_24hour": false,

    "orientation": 0,

    "show_graph": true,

    "nightscout_url": "https://nightscoutmark.herokuapp.com",

    "nightscout_access_token": "sugarpimar-c5eb3b54346e34b7",

    "unit_mmolL": false

}

**Comment by bassettb** [comment]
You should delete that message.
